### ISSUE TITLE
Escaping LaTeX special chars

### ISSUE THREAD

**Issue by syxolk** [narimiran/tably#1]
If your CSV file contains any special chars used in latex like `&` or `%` the resulting PDF file might not look as expected. Those characters must be escaped to e.g. `\&` or `\%`.

Sources:
- https://tex.stackexchange.com/a/34586
- http://www.cespedes.org/blog/85/how-to-escape-latex-special-characters

**Comment by narimiran** [comment]
> If your CSV file contains any special chars used in latex like `&` or `%` the resulting PDF file might not look as expected.

Can confirm.

The tool was originally intended for converting 'raw' CSV files (which might be created from a lab equipment) where the cells contain only numeric values, so I didn't take any precaution when it comes to special characters.  
Nonetheless, I will try to solve this in future releases.

Should a whole file be checked for those characters or just a header (first row)?

**Comment by syxolk** [comment]
This might be a minor security issue if you can't trust the CSV file, e.g. infinite loops like `\def\x{\x}\x`. However, in your use case this might not be an issue.

I vote to escape all cells in all rows.

**Comment by narimiran** [comment]
> This might be a minor security issue if you can't trust the CSV file, e.g. infinite loops like \def\x{\x}\x. 

Thanks for pointing this out, but this is currently a low priority because of the assumption that CSVs are known/simple/machine generated.  
If this kind of situation happens in a 'real-world problem', please open another issue and I'll see what can I do.

Commit f9d642681c413c96eed726008d0d9b8b1698e95f solves the problem with special characters, so I will close this issue.
